name: Crypto Data Logger

on:
  schedule:
    # Run at 3:00 AM Central (8:00 AM UTC)
    - cron: '0 8 * * *'
    # Run at 11:00 AM Central (4:00 PM UTC) 
    - cron: '0 16 * * *'
    # Run at 7:00 PM Central (12:00 AM UTC next day)
    - cron: '0 0 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  log-crypto-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas pytz
        
    - name: Run crypto logger
      run: python crypto_logger.py
      
    - name: Commit and push data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Update crypto data - $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload CSV as artifact
      uses: actions/upload-artifact@v4
      with:
        name: crypto-data-csv
        path: crypto_data.csv
        retention-days: 90
